package dmall.framework.common.constants;

import dmall.framework.common.model.MappingVO;

import java.util.HashMap;
import java.util.Map;

/**
 * Created by minjae on 2016-05-03.
 */
public class MapperConstants {
    public static final String COMMON = "common.bizCommon.";
    public static final String SYSTEM_MENU = "system.menu.";
    public static final String SYSTEM_LOGIN = "system.login.";
    public static final String SETUP_BASE_ADMINAUTHCONFIG = "setup.base.AdminAuthConfig.";
    public static final String BBS = "board.bbsManage.";
    public static final String BBS_LETT = "board.bbsLettManage.";
    public static final String BBS_INQUIRY_LETT = "board.bbsInquiryLettManage.";
    public static final String BBS_FAQ_LETT = "board.bbsFaqLettManage.";
    public static final String BBS_GOODS_LETT = "board.bbsGoodsLettManage.";
    public static final String BBS_REPLY = "board.bbsReplyManage.";
    public static final String BBS_TITLE = "board.bbsTitle.";
    public static final String BBS_CMNT = "board.bbsCmnt.";
    public static final String BBS_ATCH_FILE = "board.atchFile.";
    public static final String BBS_STYLE_LETT = "board.bbsStyleLettManage.";
    public static final String SMS = "operation.smsManage.";
    public static final String EMAIL = "operation.emailManage.";
    public static final String BANNED_BASE = "operation.bannedManage.";
    public static final String REPLACE_CD = "operation.replaceCd.";
    public static final String DESIGN_POPUP = "design.popupManage.";
    public static final String DESIGN_DISPLAY = "design.displayManage.";
    public static final String DESIGN_BANNER = "design.bannerManage.";
    public static final String DESIGN_HTML_EDIT = "design.htmlEdit.";
    public static final String DESIGN_SKIN = "design.skinConfig.";
    public static final String DESIGN_ICON = "design.iconManage.";
    public static final String GOODS_MAIN_DISPLAY = "goods.mainDisplay.";
    public static final String BRAND_MANAGE = "goods.brand.";
    public static final String CATEGORY_MANAGE = "goods.category.";
    public static final String FILTER_MANAGE = "goods.filter.";
    public static final String KEYWORD_MANAGE = "goods.keyword.";
    public static final String MEMBER_INFO = "member.info.";
    public static final String MEMBER_ACCOUNT = "member.refundAccount.";
    public static final String MEMBER_DELIVERY = "member.delivery.";
    public static final String MEMBER_INTEREST = "member.interest.";
    public static final String MEMBER_MANAGE = "member.manage.";
    public static final String MEMBER_MANAGE_DORMANT = "member.manageDormant.";
    public static final String MEMBER_MANAGE_WITHDRWAL = "member.manageWithdrawal.";
    public static final String MEMBER_LEVEL = "member.level.";
    public static final String GOODS_MANAGE = "goods.manage.";
    public static final String FREEBIE_MANAGE = "goods.freebie.";
    public static final String RECOMMEND_MANAGE = "goods.recommend.";
    public static final String SETUP_DELIVERY = "setup.delivery.";
    public static final String SAVEDMN_POINT = "operation.savedMnPoint.";
    public static final String RESTOCK_NOTIFY = "goods.restocknotify.";
    public static final String SETUP_PERSON_CERTIFY = "setup.personcertify.";
    public static final String SETUP_ORDER_CONFIG = "setup.order.config.";
    public static final String SETUP_SITE_INFO = "setup.siteInfo.";
    public static final String SETUP_TERM_CONFIG = "setup.term.config.";
    public static final String SETUP_SAVED_MONEY_CONFIG = "setup.savedmoney.config.";
    public static final String SETUP_TAXBILL_CONFIG = "setup.taxbill.config.";
    public static final String SETUP_POINT_CONFIG = "setup.point.config.";
    public static final String SETUP_MEMBER_INFO = "setup.memberinfo.";
    public static final String SETUP_PAYMENT_MANAGE = "setup.paymentManage.";
    public static final String SETUP_SNS_MANAGE = "setup.sns.config.";
    public static final String SETUP_SECURITY_MANAGE = "setup.securityManage.";
    public static final String SETUP_DELIVERY_INTERFACE = "setup.delivery.interface.";
    public static final String PROMOTION_COUPON = "promotion.coupon.";
    public static final String PROMOTION_FREBIECNDT = "promotion.freebieCndt.";
    public static final String PROMOTION_EVENT = "promotion.event.";
    public static final String PROMOTION_EXHIBITION = "promotion.exhibition.";
    public static final String PROMOTION_TIMEDEAL = "promotion.timeDeal.";
    public static final String ORDER_MANAGE = "order.manage.";
    public static final String ORDER_REFUND = "order.refund.";
    public static final String ORDER_EXCHANGE = "order.exchange.";
    public static final String ORDER_DELIVERY = "order.delivery.";
    public static final String ADMIN_MAIN = "admin.main.";
    public static final String ORDER_DEPOSIT = "order.deposit.";
    public static final String ORDER_SALES_PROOF = "order.salesproof.";
    public static final String ORDER_RSV = "order.reservation.";
    public static final String BASKET = "basket.";
    public static final String SYSTEM_LINK_DOORTODOOR = "system.link.doortodoor.";
    public static final String SETUP_SEO_CONFIG = "setup.opersupport.";
    public static final String VSTR_ANLS = "statistics.vstrAnls.";
    public static final String VISIT_PATH_ANLS = "statistics.visitPathAnls.";
    public static final String VISIT_IP_ANLS = "statistics.visitIpAnls.";
    public static final String NW_MEMBER_ANLS = "statistics.nwMemberAnls.";
    public static final String MEMBER_SVMN_ANLS = "statistics.memberSvmnAnls.";
    public static final String CTG_GOODS_ANLS = "statistics.ctgGoodsAnls.";
    public static final String SYSTEM_SITE = "system.site.";
    public static final String SALE_RANK_GOODS_ANLS = "statistics.saleRankGoodsAnls.";
    public static final String BASKET_GOODS_ANLS = "statistics.basketGoodsAnls.";
    public static final String ORD_STTCS_ANLS = "statistics.ordSttcsAnls.";
    public static final String SALES_STTCS_ANLS = "statistics.salesSttcsAnls.";
    public static final String PAY_WAY_SALES_STTCS = "statistics.payWaySalesSttcs.";
    public static final String SELLER = "seller.";
    public static final String CALC_SELLER = "calcSeller.";
    public static final String EYESIGHT = "mypage.eyesight.";
    public static final String PRESCRIPTION = "mypage.prescription.";
    public static final String VISIT_RSV = "visit.";
    public static final String VISION_CHECK = "vision.";
    public static final String PUSH = "push.";
    public static final String HEARING_AID = "hearingaid.";
    public static final String SYSTEM_DAVISION = "system.davision.";
    public static final String LOGIN_CURRENTSTATUS_ANLS = "statistics.loginCurrentStatusAnls.";

    public static final String GLASS_BRAND_MAPPING = "glass.brand.mapping";
    public static final String CONTACT_BRAND_MAPPING = "contact.brand.maping";
    public static final String CONTACT_COLOR_MAPPING = "contact.color.maping";
    public static final String CONTACT_PERIOD_MAPPING = "contact.period.maping";

    public static final String MAPPING_METHOD_ERP_CODE = "by.erp.code";
    public static final String MAPPING_METHOD_VALUE = "by.value";

    public static final Map<String, MappingVO> GLASS_BRAND_MAP = new HashMap<String, MappingVO>() {{
        put("2567", new MappingVO<>("BBM(WEB)", "비비엠(웹)", "BBM"));
        put("2593", new MappingVO<>("BBM_PEOPLES", "비비엠_피플스", "BBM"));
        put("2606", new MappingVO<>("BBM_79_MEMORY", "비비엠_79_메모리", "BBM"));
        put("2713", new MappingVO<>("BBM_PE", "비비엠 BBM_PE", "BBM"));
        put("3649", new MappingVO<>("BBM_PE_FLEX TITAN MEMORY", "비비엠 BBM_PE_FLEX TITAN MEMORY", "BBM"));
        put("3651", new MappingVO<>("BBM_PE_T", "비비엠피플스에디션T시리즈", "BBM"));
        put("1199", new MappingVO<>("BIBIEM X CARVEN_45", "비비엠 x까르뱅_45", "BIBIEM"));
        put("1200", new MappingVO<>("BIBIEM X CARVEN_65", "비비엠 x까르뱅_65", "BIBIEM"));
        put("1201", new MappingVO<>("BIBIEM X CARVEN_69", "비비엠 x까르뱅_69", "BIBIEM"));
        put("1202", new MappingVO<>("BIBIEM X CARVEN_75", "비비엠 x까르뱅_75", "BIBIEM"));
        put("1203", new MappingVO<>("BIBIEM X CARVEN_85", "비비엠 x까르뱅_85", "BIBIEM"));
        put("1204", new MappingVO<>("BIBIEM X CARVEN_95", "비비엠 x까르뱅_95", "BIBIEM"));
        put("1898", new MappingVO<>("BIBIEM_C_55", "비비엠_커버그라운드_55", "BIBIEM"));
        put("1899", new MappingVO<>("BIBIEM_C_66", "비비엠_커버그라운드_66", "BIBIEM"));
        put("1900", new MappingVO<>("BIBIEM_C_77", "비비엠_커버그라운드_77", "BIBIEM"));
        put("2110", new MappingVO<>("BIBIEM_HB", "비비엠_한별", "BIBIEM"));
        put("2207", new MappingVO<>("BIBIEM_PL_58", "비비엠_필립_58", "BIBIEM"));
        put("2627", new MappingVO<>("BIBIEM_L", "비비엠_L", "BIBIEM"));
        put("2762", new MappingVO<>("BIBIEM_LUX", "비비엠_럭스", "BIBIEM"));
        put("2769", new MappingVO<>("BIBIEM X RODENSTOCK", "비비엠 X 로덴스톡", "BIBIEM"));
        put("2782", new MappingVO<>("BIBIEM_BESPOKE_ACC", "비비엠_비스포크_부속품", "BIBIEM"));
        put("2783", new MappingVO<>("BIBIEM_BESPOKE", "비비엠_비스포크", "BIBIEM"));
        put("2875", new MappingVO<>("BIBIEM_M_55", "비비엠_메라키_55", "BIBIEM"));
        put("2876", new MappingVO<>("BIBIEM_M_58", "비비엠_메라키_58", "BIBIEM"));
        put("2877", new MappingVO<>("BIBIEM_M_63", "비비엠_메라키_63", "BIBIEM"));
        put("2882", new MappingVO<>("BIBIEM_LKS_53", "비비엠_루카스_53", "BIBIEM"));
        put("2883", new MappingVO<>("BIBIEM_LKS_58", "비비엠_루카스_58", "BIBIEM"));
        put("2884", new MappingVO<>("BIBIEM_LKS_63", "비비엠_루카스_63", "BIBIEM"));
        put("2972", new MappingVO<>("BIBIEM_LKS_48", "비비엠_루카스_48", "BIBIEM"));
        put("2973", new MappingVO<>("BIBIEM_M_39", "비비엠_메라키_39", "BIBIEM"));
        put("2974", new MappingVO<>("BIBIEM_M_43", "비비엠_메라키_43", "BIBIEM"));
        put("3725", new MappingVO<>("BIBIEM X CARVEN_55", "비비엠 X 까르뱅_55", "BIBIEM"));
        put("3726", new MappingVO<>("BIBIEM X CARVEN_89", "비비엠 X 까르뱅_89", "BIBIEM"));
        put("3890", new MappingVO<>("BIBIEM_FL_40", "BIBIEM_FL_40", "BIBIEM"));
        put("3891", new MappingVO<>("BIBIEM_FL_45", "BIBIEM_FL_45", "BIBIEM"));
        put("3892", new MappingVO<>("BIBIEM_FL_50", "BIBIEM_FL_50", "BIBIEM"));
        put("3893", new MappingVO<>("BIBIEM_FL_55", "BIBIEM_FL_55", "BIBIEM"));
        put("3894", new MappingVO<>("BIBIEM_FL_60", "BIBIEM_FL_60", "BIBIEM"));
        put("4048", new MappingVO<>("BIBIEM", "비비엠", "BIBIEM"));
        put("4075", new MappingVO<>("BIBIEM X MARVEL", "비비엠x마블", "BIBIEM"));
        put("4079", new MappingVO<>("BIBIEM", "비비엠", "BIBIEM"));
        put("5680", new MappingVO<>("BIBIEM_GOLD", "비비엠 금테", "BIBIEM"));
        put("5712", new MappingVO<>("BIBIEM VMD", "비비엠 장", "BIBIEM"));
        put("5912", new MappingVO<>("BIBIEM X CNBLUE", "비비엠x씨엔블루", "BIBIEM"));
        put("1845", new MappingVO<>("DAON_3_D", "다온x덕진_3", "DAON"));
        put("2008", new MappingVO<>("DAON_5_R", "다온_5_리버코리아", "DAON"));
        put("2106", new MappingVO<>("DAON_5_JS", "다온_5_제이에스아이웨어", "DAON"));
        put("2543", new MappingVO<>("DAON_5_M_ULTEM(WEB)", "다온_5_M_울템(웹)", "DAON"));
        put("2544", new MappingVO<>("DAON_5_M_B-TITAN(WEB)", "다온_5_M_B-티탄(웹)", "DAON"));
        put("2592", new MappingVO<>("DAON_49TITAN", "다온_49티탄", "DAON"));
        put("2613", new MappingVO<>("DAON_SUPERPLASTIC", "다온_슈퍼플라스틱", "DAON"));
        put("2623", new MappingVO<>("DAON_3_V", "다온_3_비아리코", "DAON"));
        put("2624", new MappingVO<>("DAON_5_V", "다온_5_비아리코", "DAON"));
        put("2626", new MappingVO<>("DAON_49TITAN_S", "다온_49티탄_선경", "DAON"));
        put("2670", new MappingVO<>("DAON_5_J", "다온_5_장원산업", "DAON"));
        put("2672", new MappingVO<>("DAON_3_Y", "다온_3_와이비옵틱", "DAON"));
        put("2673", new MappingVO<>("DAON_5_Y", "다온_5_와이비옵틱", "DAON"));
        put("2676", new MappingVO<>("DAON_ULTRA_CLEANSSES", "다온_울트라_클린시스", "DAON"));
        put("2717", new MappingVO<>("DAON_VICHVERR", "DAON_VICHVERR", "DAON"));
        put("2735", new MappingVO<>("DAON_1_M", "다온x엠티옵틱스_1", "DAON"));
        put("2750", new MappingVO<>("DAON_5_W", "다온_5_우미", "DAON"));
        put("2758", new MappingVO<>("DAON_KIDS_H", "다온키즈_한별광학", "DAON"));
        put("2773", new MappingVO<>("DAON_3_A", "다온_3_에이스", "DAON"));
        put("2780", new MappingVO<>("DAON_3_K", "다온_3_케이홀릭", "DAON"));
        put("2781", new MappingVO<>("DAON_5_K", "다온_5_케이홀릭", "DAON"));
        put("2945", new MappingVO<>("DAON_3_ETO", "다온x아이탑옵티컬", "DAON"));
        put("2985", new MappingVO<>("DAON_3_JS", "다온_3_제이에스아이웨어", "DAON"));
        put("3994", new MappingVO<>("DAON_5_S", "다온x선경_5", "DAON"));
        put("4005", new MappingVO<>("DAON_7_S", "다온x선경_7", "DAON"));
        put("4032", new MappingVO<>("DAON_5_E", "다온x아이탑_5", "DAON"));
        put("4057", new MappingVO<>("DAON_5_F", "다온x팬텀_5", "DAON"));
        put("4058", new MappingVO<>("DAON_7_F", "다온x팬텀_7", "DAON"));
        put("5690", new MappingVO<>("DAON_3_H", "다온x한별_3", "DAON"));
        put("5718", new MappingVO<>("DAON_7_H", "다온x한별_7", "DAON"));
        put("5734", new MappingVO<>("DAON_3_E", "다온x아이탑_3 ", "DAON"));
        put("5736", new MappingVO<>("DAON_BLUE_7_S", "다온블루_7_선경", "DAON"));
        put("5737", new MappingVO<>("DAON_BLUE_9_S", "다온블루_9_선경", "DAON"));
        put("5739", new MappingVO<>("DAON_BLUE_7", "다온_블루_7", "DAON"));
        put("5740", new MappingVO<>("DAON_BLUE_9", "다온_블루_9", "DAON"));
        put("5774", new MappingVO<>("DAON_5", "다온_5", "DAON"));
        put("5777", new MappingVO<>("DAON_3", "다온_3", "DAON"));
        put("5786", new MappingVO<>("DAON_SUN", "다온_선", "DAON"));
        put("5926", new MappingVO<>("DAON_1", "다온_1", "DAON"));
        put("5956", new MappingVO<>("DAON_3_B", "다온_3_블랙패션", "DAON"));
        put("5985", new MappingVO<>("DAON_3_P", "다온X패션피플_3", "DAON"));
        put("5986", new MappingVO<>("LOTTO", "로또", "LOTTO"));
        put("0750", new MappingVO<>("MORGAN", "모간", "MORGAN"));
        put("2408", new MappingVO<>("MORGAN_9_S", "모간_9_STC선경", "MORGAN"));
        put("2629", new MappingVO<>("MORGAN_7_G", "모간_7_지이오디자인", "MORGAN"));
        put("2630", new MappingVO<>("MORGAN_9_G", "모간_9_지이오디자인", "MORGAN"));
        put("2671", new MappingVO<>("MORGAN_7_J", "모간_7_장원산업", "MORGAN"));
        put("2674", new MappingVO<>("MORGAN_7_Y", "모간_7_와이비옵틱", "MORGAN"));
        put("2699", new MappingVO<>("MORGAN_KIDS", "모간_키즈", "MORGAN"));
        put("2774", new MappingVO<>("MORGAN_7_B", "모간_7_블랙패션", "MORGAN"));
        put("2775", new MappingVO<>("MORGAN_9_B", "모간_9_블랙패션", "MORGAN"));
        put("2809", new MappingVO<>("MORGAN_7_M", "모간_7_미오티카", "MORGAN"));
        put("2878", new MappingVO<>("MORGAN_M.TATE", "모간x엠테이트", "MORGAN"));
        put("2964", new MappingVO<>("MORGAN_MIDAS", "모간x마이다스", "MORGAN"));
        put("2965", new MappingVO<>("MORGAN_VICHVERR", "모간_비치베르", "MORGAN"));
        put("5865", new MappingVO<>("MORGAN_7", "모간_7", "MORGAN"));
        put("5866", new MappingVO<>("MORGAN_9", "모간_9", "MORGAN"));
        put("5953", new MappingVO<>("MORGAN_9_N", "모간_9_뉴젠", "MORGAN"));
        put("1205", new MappingVO<>("SEERIES_VA_3", "시리즈_비아리코_3", "SEERIES"));
        put("1206", new MappingVO<>("SEERIES_VA_5", "시리즈_비아리코_5", "SEERIES"));
        put("1207", new MappingVO<>("SEERIES_VA_7", "시리즈_비아리코_7", "SEERIES"));
        put("1208", new MappingVO<>("SEERIES_VA_9", "시리즈_비아리코_9", "SEERIES"));
        put("1219", new MappingVO<>("SEERIES_JS_3", "시리즈_제이에스_3", "SEERIES"));
        put("1220", new MappingVO<>("SEERIES_JS_5", "시리즈_제이에스_5", "SEERIES"));
        put("1221", new MappingVO<>("SEERIES_JS_7", "시리즈_제이에스_7", "SEERIES"));
        put("1222", new MappingVO<>("SEERIES_JS_9", "시리즈_제이에스_9", "SEERIES"));
        put("1223", new MappingVO<>("SEERIES_MI_3", "시리즈_미오티카_3", "SEERIES"));
        put("1224", new MappingVO<>("SEERIES_MI_5", "시리즈_미오티카_5", "SEERIES"));
        put("1225", new MappingVO<>("SEERIES_MI_7", "시리즈_미오티카_7", "SEERIES"));
        put("1226", new MappingVO<>("SEERIES_MI_9", "시리즈_미오티카_9", "SEERIES"));
        put("2059", new MappingVO<>("SEERIES_BO_1", "시리즈_보담_1", "SEERIES"));
        put("2837", new MappingVO<>("SEERIES_WE", "시리즈_위", "SEERIES"));
        put("3035", new MappingVO<>("SEERIES_HB_3", "시리즈_한별_3", "SEERIES"));
        put("3036", new MappingVO<>("SEERIES_HB_5", "시리즈_한별_5", "SEERIES"));
        put("3037", new MappingVO<>("SEERIES_HB_7", "시리즈_한별_7", "SEERIES"));
        put("3038", new MappingVO<>("SEERIES_HB_9", "시리즈_한별_9", "SEERIES"));
        put("3659", new MappingVO<>("SEERIES_SK_5", "시리즈_선경_5", "SEERIES"));
        put("3660", new MappingVO<>("SEERIES_SK_3", "시리즈_선경_3", "SEERIES"));
        put("3661", new MappingVO<>("SEERIES_SK_7", "시리즈_선경_7", "SEERIES"));
        put("3662", new MappingVO<>("SEERIES_SK_9", "시리즈_선경_9", "SEERIES"));
        put("3664", new MappingVO<>("SEERIES_KH_3", "시리즈_케이홀릭_3", "SEERIES"));
        put("3665", new MappingVO<>("SEERIES_KH_5", "시리즈_케이홀릭_5", "SEERIES"));
        put("3666", new MappingVO<>("SEERIES_KH_7", "시리즈_케이홀릭_7", "SEERIES"));
        put("3667", new MappingVO<>("SEERIES_KH_9", "시리즈_케이홀릭_9", "SEERIES"));
        put("3671", new MappingVO<>("SEERIES_FT_7", "시리즈_팬텀_7", "SEERIES"));
        put("3672", new MappingVO<>("SEERIES_FT_9", "시리즈_팬텀_9", "SEERIES"));
        put("3673", new MappingVO<>("SEERIES_1", "시리즈_1", "SEERIES"));
        put("3674", new MappingVO<>("SEERIES_3", "시리즈_3", "SEERIES"));
        put("3675", new MappingVO<>("SEERIES_5", "시리즈_5", "SEERIES"));
        put("3676", new MappingVO<>("SEERIES_7", "시리즈_7", "SEERIES"));
        put("3677", new MappingVO<>("SEERIES_9", "시리즈_9", "SEERIES"));
        put("3683", new MappingVO<>("SEERIES_DI_7", "시리즈_대일당_7", "SEERIES"));
        put("3684", new MappingVO<>("SEERIES_DI_9", "시리즈_대일당_9", "SEERIES"));
        put("3685", new MappingVO<>("SEERIES_GD_7", "시리즈_지이오_7", "SEERIES"));
        put("3686", new MappingVO<>("SEERIES_GD_9", "시리즈_지이오_9", "SEERIES"));
        put("3687", new MappingVO<>("SEERIES_JW_5", "시리즈_장원_5", "SEERIES"));
        put("3688", new MappingVO<>("SEERIES_JW_7", "시리즈_장원_7", "SEERIES"));
        put("3689", new MappingVO<>("SEERIES_JW_9", "시리즈_장원_9", "SEERIES"));
        put("3812", new MappingVO<>("SEERIES_YB_3", "시리즈_와이비_3", "SEERIES"));
        put("3813", new MappingVO<>("SEERIES_YB_5", "시리즈_와이비_5", "SEERIES"));
        put("3814", new MappingVO<>("SEERIES_YB_7", "시리즈_와이비_7", "SEERIES"));
        put("3816", new MappingVO<>("SEERIES_RI_5", "시리즈_리버코리아_5", "SEERIES"));
        put("3821", new MappingVO<>("SEERIES_MA_7", "시리즈_마스티나_7", "SEERIES"));
        put("3895", new MappingVO<>("SEERIES_KH_ECOM", "시리즈_케이홀릭_에콤", "SEERIES"));
        put("4096", new MappingVO<>("SEERIES_WM_5", "SEERIES_WM_5", "SEERIES"));
    }};

    public static final Map<String, MappingVO> CONTACT_BRAND_MAP = new HashMap<String, MappingVO>() {{
        put("2607", new MappingVO<>("EYE-LUV 메리골드","EYE-LUV 메리골드", "다비치렌즈"));
        put("2748", new MappingVO<>("EYE-LUV 메이릴리","EYE-LUV 메이릴리", "다비치렌즈"));
        put("1368", new MappingVO<>("DAVI-VIEW","다비뷰", "다비치렌즈"));
        put("1470", new MappingVO<>("DAVICH FINEVIEW","다비치 파인뷰", "다비치렌즈"));
        put("1173", new MappingVO<>("DAVICHLENS 1M DEAR.B", "다비치렌즈 1M 디어비", "다비치렌즈"));
        put("1174", new MappingVO<>("DAVICHLENS 1M MERRYRING", "다비치렌즈 1M 메리링", "다비치렌즈"));
        put("1175", new MappingVO<>("DAVICHLENS 1M AQUA", "다비치렌즈 1M 아쿠아", "다비치렌즈"));
        put("2839", new MappingVO<>("DAVICHLENS 3DAYS NEW STARRY", "다비치렌즈 3일용 뉴스타리", "다비치렌즈"));
        put("3843", new MappingVO<>("DAVICHLENS 3DAYS AURORA", "다비치렌즈 3일용 오로라", "다비치렌즈"));
        put("3721", new MappingVO<>("DAVICHLENS 1M DEAR.B TORIC", "다비치렌즈 디어비 토릭", "다비치렌즈"));
        put("2828", new MappingVO<>("DAVICHLENS 1M LISSOM", "다비치렌즈 리썸", "다비치렌즈"));
        put("3722", new MappingVO<>("DAVICHLENS 1M IDEARING", "다비치렌즈 아이딜링", "다비치렌즈"));
        put("3723", new MappingVO<>("DAVICHLENS 1DAY DEAR.B", "다비치렌즈 원데이 디어비", "다비치렌즈"));
        put("4088", new MappingVO<>("DAVICHLENS 1DAY PURERING ", "다비치렌즈 원데이 퓨어링", "다비치렌즈"));
        put("2827", new MappingVO<>("DAVICHLENS 1M PURERING", "다비치렌즈 퓨어링", "다비치렌즈"));
        put("2840", new MappingVO<>("DAVICHLENS 1M MOOD", "다비치렌즈 한달용 무드", "다비치렌즈"));
        put("3880", new MappingVO<>("DAVICHLENS 1MONTH VELING", "다비치렌즈 한달용 베일링", "다비치렌즈"));
        put("4089", new MappingVO<>("DAVICHLENS 1M PURERING TORIC", "다비치렌즈 한달용 퓨어링 토릭", "다비치렌즈"));
        put("3678", new MappingVO<>("DAVICHLENS 1M HEIMISH", "다비치렌즈 한달용 헤이미쉬", "다비치렌즈"));
        put("2521", new MappingVO<>("단델리온", "단델리온", "다비치렌즈"));
        put("3333", new MappingVO<>("TREVUES", "뜨레뷰", "다비치렌즈"));
        put("2551", new MappingVO<>("TREVUES 3DAYS STARRY", "뜨레뷰 3일 스타리", "다비치렌즈"));
        put("2550", new MappingVO<>("TREVUES 3DAYS AQUA", "뜨레뷰 3일 아쿠아 투명", "다비치렌즈"));
        put("2741", new MappingVO<>("TREVUES 3DAYS AQUA 30P", "뜨레뷰 3일 아쿠아 투명 (30P)", "다비치렌즈"));
        put("2712", new MappingVO<>("TREVUES 3DAYS PALETTE", "뜨레뷰 3일 팔레트", "다비치렌즈"));
        put("3650", new MappingVO<>("TREVUES 3DAYS AQUA COLOR", "뜨레뷰 3일용 아쿠아 컬러", "다비치렌즈"));
        put("2499", new MappingVO<>("TREVUES 3WEEKS STARRY", "뜨레뷰 3주 스타리", "다비치렌즈"));
        put("2500", new MappingVO<>("TREVUES 3WEEKS AQUA", "뜨레뷰 3주 아쿠아 투명", "다비치렌즈"));
        put("2497", new MappingVO<>("TREVUES 3WEEKS PALETTE", "뜨레뷰 3주 팔레트", "다비치렌즈"));
        put("2456", new MappingVO<>("TREVUES 3WEEKS EYE PICK", "뜨레뷰 3주용 아이픽", "다비치렌즈"));
        put("5997", new MappingVO<>("TREVUES PC 3일(지오)", "뜨레뷰 PC 3일(지오)", "다비치렌즈"));
        put("5971", new MappingVO<>("TREVUES SI-H 3일 신제품", "뜨레뷰 SI-H 3일 신제품", "다비치렌즈"));
        put("2072", new MappingVO<>("TREVUES 3DAYS NEWRISH", "뜨레뷰 뉴리시", "다비치렌즈"));
        put("2096", new MappingVO<>("TREVUES 3DAYS NEW MIRACLE 120P", "뜨레뷰 뉴미라클 120P", "다비치렌즈"));
        put("2095", new MappingVO<>("TREVUES 3DAYS NEW MIRACLE 20P", "뜨레뷰 뉴미라클 20P", "다비치렌즈"));
        put("1176", new MappingVO<>("TREVUES 3DAYS DOLCERING", "뜨레뷰 돌체링 3DAY", "다비치렌즈"));
        put("2093", new MappingVO<>("TREVUES 3DAYS MERSEE", "뜨레뷰 메르시", "다비치렌즈"));
        put("2071", new MappingVO<>("TREVUES 3DAYS BALANSEE", "뜨레뷰 밸런시", "다비치렌즈"));
        put("2098", new MappingVO<>("TREVUES 3DAYS BALANSEE 대용량", "뜨레뷰 밸런시 대용량", "다비치렌즈"));
        put("5691", new MappingVO<>("TREVUES BOTTLE", "뜨레뷰 병렌즈 ", "다비치렌즈"));
        put("2094", new MappingVO<>("TREVUES 3DAYS SKATCH", "뜨레뷰 스카치", "다비치렌즈"));
        put("5847", new MappingVO<>("TREVUES SI-H 3일(뉴바이오)", "뜨레뷰 실리콘 3일(뉴바이오)", "다비치렌즈"));
        put("5848", new MappingVO<>("TREVUES SI-H 3주(뉴바이오)", "뜨레뷰 실리콘 3주(뉴바이오)", "다비치렌즈"));
        put("5754", new MappingVO<>("TREVUES SI-H 1달(디케이)", "뜨레뷰 실리콘 먼슬리", "다비치렌즈"));
        put("5684", new MappingVO<>("TREVUES SI-H 3일(디케이)", "뜨레뷰 실리콘 쓰리데이", "다비치렌즈"));
        put("5685", new MappingVO<>("TREVUES SI-H 3주(디케이)", "뜨레뷰 실리콘 쓰리위크", "다비치렌즈"));
        put("2469", new MappingVO<>("TREVUES 1DAY", "뜨레뷰 원데이", "다비치렌즈"));
        put("4003", new MappingVO<>("TREVUES JUNIOR", "뜨레뷰 쥬니어", "다비치렌즈"));
        put("2209", new MappingVO<>("TREVUES 3DAYS COCORING", "뜨레뷰 코코링", "다비치렌즈"));
        put("5845", new MappingVO<>("TREVUES(뉴바이오)", "뜨레뷰(뉴바이오)", "다비치렌즈"));
        put("5846", new MappingVO<>("TREVUES(엔보이)", "뜨레뷰(엔보이)", "다비치렌즈"));
        put("2481", new MappingVO<>("TREVUES SI-H 3일 투명 10P(뉴바", "뜨레뷰실리콘3일투명 10P", "다비치렌즈"));
        put("5968", new MappingVO<>("TREVUES SI-H 3일 투명 30P(뉴바", "뜨레뷰실리콘3일투명 30P", "다비치렌즈"));
        put("3356", new MappingVO<>("만세삼창", "만세삼창", "다비치렌즈"));
        put("5839", new MappingVO<>("만세삼창(뉴바이오)", "만세삼창(뉴바이오)", "다비치렌즈"));
        put("5841", new MappingVO<>("만세삼창(드림콘)", "만세삼창(드림콘)", "다비치렌즈"));
        put("5840", new MappingVO<>("만세삼창(맥스룩)", "만세삼창(맥스룩)", "다비치렌즈"));
        put("5842", new MappingVO<>("만세삼창(엔보이)", "만세삼창(엔보이)", "다비치렌즈"));
        put("2596", new MappingVO<>("EYE LUV 1+2 (렌즈클릭)", "아이럽 1+2 (렌즈클릭)", "다비치렌즈"));
        put("2594", new MappingVO<>("EYE LUV 1+2 (엔보이)", "아이럽 1+2 (엔보이)", "다비치렌즈"));
        put("2595", new MappingVO<>("EYE LUV 1+2 (오조)", "아이럽 1+2 (오조)", "다비치렌즈"));
        put("2597", new MappingVO<>("EYE LUV 1+2 (휴먼)", "아이럽 1+2 (휴먼)", "다비치렌즈"));
        put("2546", new MappingVO<>("EYE-LUV DAHLIA", "아이럽 다알리아", "다비치렌즈"));
        put("5947", new MappingVO<>("EYE LUV(렌즈클릭)", "아이럽(렌즈클릭)", "다비치렌즈"));
        put("1421", new MappingVO<>("EYE LUV(병)", "아이럽(병)", "다비치렌즈"));
        put("5946", new MappingVO<>("EYE LUV(아이콘)", "아이럽(아이콘)", "다비치렌즈"));
        put("5843", new MappingVO<>("EYE LUV (엔보이)", "아이럽(엔보이)", "다비치렌즈"));
        put("5916", new MappingVO<>("EYE LUV (오조)", "아이럽(오조)", "다비치렌즈"));
        put("5763", new MappingVO<>("EYE LUV(지오)", "아이럽(지오)", "다비치렌즈"));
        put("5844", new MappingVO<>("EYE LUV(팩)", "아이럽(팩)", "다비치렌즈"));
        put("5923", new MappingVO<>("EYE LUV(휴먼)", "아이럽(휴먼)", "다비치렌즈"));
        put("2760", new MappingVO<>("EYE-LUV LIGHT", "아이럽라이트", "다비치렌즈"));
        put("2979", new MappingVO<>("1THE LENS", "원더렌즈", "다비치렌즈"));
        put("2097", new MappingVO<>("1THE LENS 대용량", "원더렌즈 90P", "다비치렌즈"));
        put("2740", new MappingVO<>("TENSEAN", "텐션", "다비치렌즈"));
        put("2749", new MappingVO<>("TENSEAN HALF", "텐션 하프팩", "다비치렌즈"));
        put("3394", new MappingVO<>("TENTEN DAILY", "텐텐 데일리", "다비치렌즈"));
        put("2533", new MappingVO<>("TENTEN MI-U", "텐텐 미유", "다비치렌즈"));
        put("2591", new MappingVO<>("TENTEN INNERIS", "텐텐 이너리스", "다비치렌즈"));
        put("2549", new MappingVO<>("TENTEN COLORING", "텐텐 컬러링", "다비치렌즈"));
        put("5815", new MappingVO<>("TWILIGHT", "트와일라잇", "다비치렌즈"));
        put("1356", new MappingVO<>("FINEVIEW", "파인뷰", "다비치렌즈"));

        put("4082", new MappingVO<>("VIVIENNEWESTWOOD 1month", "비비안웨스트우드 먼슬리", "마이피픈"));
        put("4083", new MappingVO<>("VIVIENNEWESTWOOD 1day", "비비안웨스트우드 원데이", "마이피픈"));
        put("4080", new MappingVO<>("FIPN 1month", "피픈 먼슬리", "마이피픈"));
        put("4081", new MappingVO<>("FIPN 1day", "피픈 원데이", "마이피픈"));
        put("2109", new MappingVO<>("FIPN COMPANY", "피픈컴퍼니", "마이피픈"));
        put("4084", new MappingVO<>("HEYKIM", "헤이킴", "마이피픈"));

        put("1501", new MappingVO<>("NATURELLE", "내츄렐", "바슈롬"));
        put("0408", new MappingVO<>("BAUSCH&LOMB", "바슈롬", "바슈롬"));

        put("0044", new MappingVO<>("CIBA", "시바", "알콘"));

        put("0579", new MappingVO<>("ACUVUE", "아큐브", "아큐브"));

        put("1081", new MappingVO<>("BIOFINITY", "바이오피니티", "쿠퍼비전"));
        put("2302", new MappingVO<>("BIOFINITY TORIC", "바이오피니티 토릭", "쿠퍼비전"));
        put("2529", new MappingVO<>("CLARITI", "클래리티", "쿠퍼비전"));
        put("1069", new MappingVO<>("PROCLEAR", "프로클리어", "쿠퍼비전"));
        put("3103", new MappingVO<>("PROCLEAR MF", "프로클리어멀티포컬", "쿠퍼비전"));

        put("1299", new MappingVO<>("AUNO", "아우노", "하드렌즈"));
        put("1302", new MappingVO<>("AQUILA", "아퀼라", "하드렌즈"));
        put("1301", new MappingVO<>("ATRE", "아트레", "하드렌즈"));
        put("1300", new MappingVO<>("자연주의ETC", "자연주의ETC", "하드렌즈"));
        put("2001", new MappingVO<>("FREE-AN", "프리안", "하드렌즈"));
        put("2526", new MappingVO<>("FREE-AN INDIVIDUAL", "프리안 인디비쥬얼", "하드렌즈"));
    }};

    public static final Map<String, MappingVO> CONTACT_COLOR_MAP = new HashMap<String, MappingVO>() {{
        put("100", new MappingVO<>("바이올렛","퍼플"));
        put("030", new MappingVO<>("초코","기타"));
        put("060", new MappingVO<>("레드", "기타"));
        put("070", new MappingVO<>("옐로우", "기타"));
        put("110", new MappingVO<>("혼혈", "기타"));
    }};

    public static final Map<String, MappingVO> CONTACT_PERIOD_MAP = new HashMap<String, MappingVO>() {{
        put("3M", new MappingVO<>("3개월", "3개월 이상"));
        put("6M", new MappingVO<>("6개월", "3개월 이상"));
        put("1Y", new MappingVO<>("1년",   "3개월 이상"));
        put("2Y", new MappingVO<>("2년",   "3개월 이상"));
    }};
}
