properties:
  log:
    root.name: web

---
spring:
  profile: local
properties:

---
spring:
  profile: dev
properties:

---
spring:
  profile: sandbox
properties:

---
spring:
  profile: stage
properties:
