properties:

#  dmall.framework.common.cache.CacheManagerFactoryBean 을 이용하여 ehCache 를 관리한다.
#  message 용 cache
#  1. 필수 설정
#  name=cache 이름
#  eternal= true or false : 영속성 설정, true이면 time out 등으로 소멸되지 않음
#  maxElementsInMemory= 메모리에 생성되는 최대 객체의 수
#  overflowToDisk= true or false : 인-메모리(In-Memory) 캐시가 maxInMemory 한계값에 도달하게 될 때 엘리먼트들이 유출될 수 있음을 설정
#
#  2. 옵션 설정
#  diskPersistent="false" - 캐시를 디스크에 저장 여부
#  timeToIdleSeconds= eternal이 false 일때만 설정 가능, 0 이면 무한하게 idle 상태로 유지 됨
#  timeToLiveSeconds=소멸될때 까지 최대 시간, 0이면 무한하게 설정
#  memoryStoreEvictionPolicy="LRU" -Least Recently Used

  cache.default.eternal: false
  cache.default.maxElementsInMemory: 20000
  cache.default.overflowToDisk: false
  cache.default.diskPersistent: false
  cache.default.timeToIdleSeconds: 0
  cache.default.timeToLiveSeconds: 600
  cache.default.memoryStoreEvictionPolicy: LRU
  cache.common.name: commonCache
  cache.common.eternal: false
  cache.common.maxElementsInMemory: 100
  cache.common.overflowToDisk: false
  cache.common.diskPersistent: false
  cache.common.timeToIdleSeconds: 0
  cache.common.timeToLiveSeconds: 0
  cache.common.memoryStoreEvictionPolicy: LRU
  cache.bootstrapAsynchronously: true
  cache.maximumChunkSizeBytes: 5000000
  cache.peerDiscovery: automatic
  cache.multicastGroupAddress: 230.1.1.1
  # admin: 4445, batch: 4446, image: 4447, interface.mall: 4448, mobile: 4449, web: 4450
  cache.multicastGroupPort: 4446
  cache.timeToLive: 32
  # admin: 40005, batch: 40006, image: 40007, interface.mall: 40008, mobile: 40009, web: 40010
  cache.port: 40005
  cache.socketTimeoutMillis: 20000

---
spring:
  profile: local
properties:
  cache.multicastGroupAddress: 230.1.1.2
---
spring:
  profile: dev
properties:
  cache.multicastGroupAddress: 230.1.1.2
---
spring:
  profile: sandbox
properties:
  cache.multicastGroupAddress: 230.1.1.2
---
spring:
  profile: stage
properties:
